### ISSUE TITLE
Repeated projects when scroll down

### ISSUE THREAD

**Issue by raulvillares** [mubaris/curiosity#11]
You keep getting the same projects time and time again when you scroll down.

**Comment by mubaris** [comment]
I see now. It wasn't there before. I don't know why it's happening.

**Comment by raulvillares** [comment]
Maybe you didn't notice it?

The getData function is retrieving **and rendering** the whole data everytime is called (at the beginning and everytime you scroll down).

A possible solution could be change getData so it just stores data in an array (**no rendering**). Then a new function will render that data by blocks of, for example, 10. This new function will be called at the beginning and everytime you scroll down (**getData just at the beginning**).

Though I'm not sure it's the best solution...

**Comment by mubaris** [comment]
I was using that method, but the data we are getting are **very large** and the it used hell lot of memory.

**Comment by raulvillares** [comment]
You're right. Maybe now is not a problem because the total number of projects starred by all the github users selected is (more or less) 72.

But if the number of users selected grows (and specially if the application's users are allowed to add and remove github users in the future) storing all data in memory is not an acceptable solution.

Still, there's a need for rendering the data "by blocks". Every call to getData should render a limited number of projects.

Maybe getData could select a limited number of github users (for example, 5) and render the projects starred by those 5 users.

I'm relatively new at javascript and web development so maybe somebody with more experience comes up with a better option.

**Comment by mubaris** [comment]
Doing by this will be better. I'll look into it.

**Comment by raulvillares** [comment]
Shouldn't this issue be closed? Thanks.
