### ISSUE TITLE
Add some tooling.

### ISSUE THREAD

**Issue by alejandronanez** [mubaris/curiosity#15]
What about adding some eslint / prettier / .editorconfig or maybe some build system?

I'll be down for helping with some of those.

Thanks!

And great project BTW

**Comment by mubaris** [comment]
Thanks for the suggestion @alejandronanez. Actually, I was planning to setup Travis CI for now. And I'm always welcome to contributions. Send a PR.

**Comment by alejandronanez** [comment]
Sounds good!

Will do then!

**Comment by mubaris** [comment]
@alejandronanez Maybe you wanna checkout [coala](https://github.com/coala/coala) to combine **ESlint** & **csslint**.

If you're working on it, make a new branch for it. Then send PR. :smile:

**Comment by alejandronanez** [comment]
Cool! Will check that out!

**Comment by raulvillares** [comment]
Is it possible that some of those new tooling changed some varibables (var or let keyword) to constants (const keyword) ?

For example: **const projectsPerPage** at main.js can't be modified from languageSelector.js (It was a **var projectsPerPage** at previous commit). I'm fixing it for isse #18 but I'm afraid it would happen again.

This is another problem of the current lack of modularization (see issue #17 )

**Comment by mubaris** [comment]
I'm working on #17 , I think I will use `webpack`

If you declare varibles on the top, it won't be an issue. I think that's okay. Then you can declare `var`. If you want to declare `var` in the middle of other code, use `"no-var": "off"` in `.eslintrc.json`

**Comment by alejandronanez** [comment]
I think the change from var->const was possible. And yes that's a problem of having globals leaking all over the place. Maybe a quick search/replace to fix this in the short term. :(
