### ISSUE TITLE
Selector UI fixes

### ISSUE THREAD

**Issue by mubaris** [mubaris/curiosity#19]
We need to change the UI of `Language Selector` and `Username Selector`. Here is the things to do.

- [x] Change color of Username Selector to `Orange` color used in the project.
- [x] Reduce the font size of both selectors by a small factor.
- [ ] Reduce the font of text like `Show more languages`, `Show less username`, `Add more username` & `Remove username`.

**Comment by mubaris** [comment]
CC: @maiquynhtruong

**Comment by mubaris** [comment]
@maiquynhtruong I have edited the comment, now you need to reduce the font of specified texts to make it look symmetric. So, send a PR :smile:

**Comment by maiquynhtruong** [comment]
I don't know how to do preview, so I took a snapshot

![image](https://cloud.githubusercontent.com/assets/10360577/26463041/0c8c63ec-4151-11e7-9c78-81fd9a9d20f2.png)

Do you want something like this?

**Comment by mubaris** [comment]
Yep. That's what I want. Thank you.
