### ISSUE TITLE
Add Language Sorting Functionality

### ISSUE THREAD

**Issue by mubaris** [mubaris/curiosity#4]
It would be awesome if there's a method to sort out projects according to programming languages they used.

**Comment by raulvillares** [comment]
Do you think it would be useful a filter selection? [Something like the right side of this page](https://github.com/search?utf8=✓&q=up-for-grabs&type=).

**Comment by mubaris** [comment]
Well, that's what I had in my mind. @raulvillares It will be cool if you work on that.

**Comment by raulvillares** [comment]
I'm on it.

**Comment by mubaris** [comment]
We have implemented the basic Language Filter. So, I'm closing this now. And #18 Will open
