### ISSUE TITLE
Change README

### ISSUE THREAD

**Issue by mubaris** [mubaris/curiosity#70]
Change addresses and screenshots in the README

**Comment by LeonardoBonetti** [comment]
Hey Mubaris, i did a pull request, but I dont know if is what you asked. I just found two broken links in the README and i change one, that is correctly? please send me a feedback(i'm a newbie contributor).

**Comment by maybebored** [comment]
what do you mean addresses?

**Comment by mubaris** [comment]
We recently changed web addresses of the app.

**Comment by maybebored** [comment]
Please check the latest pull request

**Comment by lauragift21** [comment]
Hi, it seems this is issue has already been resolved. Closing it will be helpful for other contributors.
