### ISSUE TITLE
Confusing project name when repository author/organization isn't shown

### ISSUE THREAD

**Issue by sompylasar** [mubaris/curiosity#75]
Example of a confusing name:
```
go - A high-performance 100% compatible drop-in replacement of "encoding/json"
```
in fact, it's https://github.com/json-iterator/go , so having a full name would be less confusing:
```
json-iterator/go - A high-performance 100% compatible drop-in replacement of "encoding/json"
```

Refs https://github.com/mubaris/curiosity/issues/49

**Comment by sompylasar** [comment]
Where the author/organization name equals the repository name, one of them can be omitted. Example:
```
probot - 🤖 A framework for building GitHub Apps to automate and improve your workflow
```
which is https://github.com/probot/probot

**Comment by mubaris** [comment]
Are you saying that "Curiosity" is a confusing name?

**Comment by sompylasar** [comment]
> Are you saying that "Curiosity" is a confusing name?

@mubaris Of course not! Confusing is what it shows. A project named "json-iterator/go" (makes sense, a JSON iterator in Go) is shown as just "go" (makes no sense to me).

**Comment by mubaris** [comment]
Then, what do you suggest?

**Comment by sompylasar** [comment]
@mubaris Please read again: "having a full name would be less confusing".

**Comment by mubaris** [comment]
> having a full name would be less confusing

I understand this.

Do you want me to move this to an organization?

**Comment by sompylasar** [comment]
I'm sorry but I don't think you hear me. It's not about "Curiosity" project name. It's about a few project names displayed in the feed.

**Comment by mubaris** [comment]
Got it. Sorry about this whole confusion

**Comment by mubaris** [comment]
Will update it now

**Comment by mubaris** [comment]
Fixed it. Closing this issue now.

**Comment by sompylasar** [comment]
👍
