### ISSUE TITLE
Hide Description if not available

### ISSUE THREAD

**Issue by haganbmj** [mubaris/curiosity#9]
If a repository does not have a description set then `null` is displayed.

**Comment by mubaris** [comment]
I'll work on that :+1:

**Comment by raulvillares** [comment]
@mubaris do you mind if I work on that? I'm looking for my first contribution to the community and I think this issue is the right one. Besides, I will like to go on further colaborating to this project.

**Comment by mubaris** [comment]
This project is always open to contributions. Also, at the moment I am too busy with my exams. So, @raulvillares please feel free to collaborate. Thanks :+1:
